### ISSUE TITLE
Load cdd_data_forindex.tsv to BigQuery

### ISSUE THREAD

**Issue by christiam** [NCBI-Codeathons/The_Virus_Index#14]
Hi @Sapsanas  , @alexandreefremovnih ,
     Could you please coordinate to move the data in this file on to BigQuery? Subsequently we can coordinate as well to provide this via the API (see #9 ).
Thanks, regards,

Christiam

**Comment by alexandreefremovnih** [comment]
Was done yesterday.

**Comment by christiam** [comment]
Moving comments from @Sapsanas to rescue from Slack:

> I had a look on the structure of the file and as I understood it is suitable for testing both

```
function name: get_SRAs_where_CDD_is_found(cdd_id)
- input: CDD ID (String) - only viral ones for now.
- output: SRA ID (list of strings)
(since it contains both CDD ID in the format CDD:xxxxx and SRA run accession)
```
