### ISSUE TITLE
Collaborate with other teams

### ISSUE THREAD

**Issue by christiam** [NCBI-Codeathons/The_Virus_Index#2]
Outline of questions for other teams:

* What's the use cases? What question are you trying to answer?
* Attributes for sequence data. 
  * From brainstorm:
     * Biome
     * Domains 
     * Geographical location
     * Isolation
     * Is there hierarchical data?
     * Temporal data
     * Data already in SRA: Taxonomy?
     * Some confidence value for the taxonomic classification? 
* How to access this data? 
* Is data interlinked or interdependent? If yes, how?

**Comment by sejmodha** [comment]
__Host phage group__

Output:
* Table 1 - Hosts and phages associated with them and additional metadata e.g. lytic, lysogenic
   * Virus taxonomy IDs and GenBank accession numbers will be provided
* Table 2 - Virus and features 
   * Columns: TaxID (Viruses), tRNA, CRISPR signatures, other suitable features, aggregate score (or confidence score?)

Methods:
Anticipated user input  - contigs or known viruses and perform BLAST based searches against CRIPR, tRNA etc databases
Individual contigs will not saved. 

__Virus graphs group__

Output:
* A standard VCF file with additional columns that contain information about taxonomy ID and Genbank accessions
   * A graph could be at the different taxonomic level, eg. graph could represent data at genus or family level

We will design a table that links that graphs data with the virus data and provide links to downloadable files - most likely to be VCF files.

__Taxonomy domain group__

HMM based models and domains - custom built

Outputs:
* Table 1: Seq ID, Taxonomy IDs
* Table 2: Seq ID, (HMM)Domain IDs, SRA ID??
* Table 3: (HMM)Domain ID, Taxonomy IDs

Note: Confidence level for assignments? Is it possible to incorporate the SRA IDs?

Methods:
* Team will use existing contigs sequence generated from various SRA datasets

__Domain HMM group__

CDD based models

Output:
* Table: Seq ID(contigs or reads), SRA ID, CDD ID, start, stop, score

Note: Taxonomic IDs for CDDs? [example](https://www.ncbi.nlm.nih.gov/Structure/cdd/cddsrv.cgi?uid=278910)
