### ISSUE TITLE
Cheat sheet for big query

### ISSUE THREAD

**Issue by christiam** [NCBI-Codeathons/The_Virus_Index#3]

**Comment by alexandreefremovnih** [comment]
Data source defined as viasq - accessible from any VM in the project. IF you know SQL, treat data source as you would schema.

Syntax of query: 
`bq query "query text"`

example:
`bq query "select * from viasq.accessions2species"`

Complete command line reference:

https://cloud.google.com/bigquery/docs/reference/bq-cli-reference

**Comment by alexandreefremovnih** [comment]
Data loaded so far:
viasq.accessions2species (from Ryan Connor)
viasq.cdd_data (from Domain HMM Boundaries team)
viasq.virushostdb (from Cody Glickman)

**Comment by alexandreefremovnih** [comment]
More data loaded:
viasq.cdd_data_original (from Domain HMM Boundaries team)
viasq.cdd_data_filtered (from Domain HMM Boundaries team) -  subset of _original, where anything with e value higher than 10^10 were removed

**Comment by alexandreefremovnih** [comment]
viasq.taxonomy_3k (from Taxonomy Domain Integration team).
Taxonomic classification for 3000 samples. These contigs were classified by mapping to viral references using MASH, so only 1834 samples have some hits.

**Comment by alexandreefremovnih** [comment]
viasq.raw_penton_hmm_results (from Taxonomy Domain Integration team)

**Comment by alexandreefremovnih** [comment]
viasq.spacer_db (from Host/Phage Interactions team)

**Comment by alexandreefremovnih** [comment]
viasq.hiv_a_j_refs_k41_t2_annotated_fakeoutput (from Virus Graphs team)

**Comment by alexandreefremovnih** [comment]
viasq.raw_penton_hmm_results (from Taxonomy Domain Integration team).

**Comment by alexandreefremovnih** [comment]
viasq.known_interactions_db (from Host/Phage Interactions team)

**Comment by alexandreefremovnih** [comment]
viasq.combined_knows_interactions (from Host/Phage Interactions team) - better, slightly expanded version of earlier viasq.known_interactions_db
