### ISSUE TITLE
Draft python API based on uses cases

### ISSUE THREAD

**Issue by christiam** [NCBI-Codeathons/The_Virus_Index#5]
Create a draft python API based on [virus discovery 2](https://github.com/search?q=topic%3Ancbi-virus-discovery-2+org%3ANCBI-Codeathons&type=Repositories) group use cases that would facilitate access to the index

**Comment by joanmarticarreras** [comment]
Example queries to BigQuery:

- [ ] GET Viral TaxID BY CDD
- [ ] GET Viral TaxID BY Host TaxID
- [ ] GET Host TaxID BY Viral TaxID
- [ ] GET GenBank accession number BY Viral TaxID
- [ ] GET Viral Graph BY CDD
- [ ] GET Viral Graph BY Viral TaxID
- [ ] GET Viral TaxID BY Viral Species Name **NOTE** This can be troublesome

**Comment by sejmodha** [comment]
__DRAFT__

Operations supported

* ~~function: get_phage_metadata(virus_taxid)~~
  * ~~input: taxid from virus (integer)~~
  * ~~output: metadata = tRNA sites?, CRISPR ?~~

* function name: get_viruses_for_host_taxonomy(taxid)
   * input: taxonomy ID for the host (integer)
   * output: virus_name (list of strings)

* function name: get_host_from_virus_taxonomy
  * description: Gets the hosts that can be infected for a given virus taxonomy ID
  * input: virus taxonomy ID (integer)
  * output: list of possible host_name (list of strings)

* function name: get_virus_host_interactions_from_confidence_level
  * description: Gets the virus-host interactions for given confidence level
  * input: confidence_level
  * output: virus_taxid, host_taxid

* function name: get_SRAs_where_CDD_is_found(cdd_id)
   * input: CDD ID (String) - only viral ones for now.
   * output: SRA ID (list of strings)

* function name: get_domains (FUTURE work)
  * input: virus_taxid
  * output: HMM domains, score, possibly, from David's group: CDDs, locations?

* function name: virus_graph(virus_taxonomy_id)
  * input: virus_taxonomy_id
  * output: if exists, a VCF file that represents the graph
  ~QUESTION: where is the unpublished/non-genbank data? What's the input if not in genbank?~
  * Can we have a database of graphs, on top of which we could map models to?

**Comment by joanmarticarreras** [comment]
* function name: get_SRA_runs_that_contain_a_virus
```
  input: virus_taxid (integer)
  output: SRA list (list of strings)
```


* function name: get_all_viruses_from_SRA
```
  input: SRA (string)
  output: virus_taxid (list of integers)
```

* function name: get_metadata_SRA
```
  input: value metadata_field
  output: SRA list if true
```

**Comment by christiam** [comment]
> * function name: get_SRA_runs_that_contain_a_virus
> 
> ```
>   input: virus_taxid (integer)
>   output: SRA list (list of strings)
> ```
> 
> * function name: get_all_viruses_from_SRA
> 
> ```
>   input: SRA (string)
>   output: virus_taxid (list of integers)
> ```
> 
> * function name: get_metadata_SRA
> 
> ```
>   input: value metadata_field
>   output: SRA list if true
> ```

Per discussion with @sejmodha , this is from data in the previous codeathon, so we'll leave it out for now.

**Comment by sejmodha** [comment]
CRISPR spacer database

* function: get_spacer_seqs
    * description: Get all spacers for a given (bacterial or archaeal) taxonomy IDs
    * input: taxonomy_id
    * output: spacer_seq(s)

* function: get_organism_from_spacer_seqs
    * description: Get all organisms (bacteria or viral) taxonomy IDs where input spacer sequence is found
    * input: spacer_seq
    * output: taxonomy_id_list
