### ISSUE TITLE
Load Ryan's table to BigQuery

### ISSUE THREAD

**Issue by christiam** [NCBI-Codeathons/The_Virus_Index#7]
Data file:
[ryan-data.csv.gz](https://github.com/NCBI-Codeathons/The_Virus_Index/files/3809428/ryan-data.csv.gz)

**Comment by christiam** [comment]
@alexandreefremovnih  - this is done, right? If so, what's the table name?

**Comment by alexandreefremovnih** [comment]
viasq.accessions2species
