### ISSUE TITLE
NCBI's data dumps

### ISSUE THREAD

**Issue by joanmarticarreras** [NCBI-Codeathons/The_Virus_Index#8]
Data dumps needed from NCBI:

- [ ] Viral GenBank accession numbers : Viral TaxID - TBD
- [ ] Viral TaxID : Viral Species Name - script: python/taxid2name.py 
- [ ] Viral TaxID : Host TaxID - Cody will provide this data
- [ ] Host TaxID : Host Species Name - script: python/taxid2name.py

**Comment by christiam** [comment]
Request from [Cody](https://github.com/glickmac)
* get the taxids (and possibly lineage?) from the text files attached

[Bacterial_Hosts.txt.gz](https://github.com/NCBI-Codeathons/The_Virus_Index/files/3809541/Bacterial_Hosts.txt.gz)
[Viruses_Taxonomy.txt.gz](https://github.com/NCBI-Codeathons/The_Virus_Index/files/3809542/Viruses_Taxonomy.txt.gz)

**Comment by christiam** [comment]
> Request from [Cody](https://github.com/glickmac)
> 
> * get the taxids (and possibly lineage?) from the text files attached
> 
> [Bacterial_Hosts.txt.gz](https://github.com/NCBI-Codeathons/The_Virus_Index/files/3809541/Bacterial_Hosts.txt.gz)
> [Viruses_Taxonomy.txt.gz](https://github.com/NCBI-Codeathons/The_Virus_Index/files/3809542/Viruses_Taxonomy.txt.gz)

This is done :)
