### ISSUE TITLE
Implement first draft API

### ISSUE THREAD

**Issue by christiam** [NCBI-Codeathons/The_Virus_Index#9]
Follow up to issue #5 .

# Action items
* Implement all functions in https://github.com/NCBI-Codeathons/The_Virus_Index/blob/master/viral_index/client.py

**Comment by joanmarticarreras** [comment]
I'll be handling  `get_viruses_for_host_taxonomy`  and `get_host_from_virus_taxonomy` API method as break to writing (I almost finished the introduction to the paper 👍 ).

**Comment by christiam** [comment]
Thanks Joan!
